
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class StokEkle extends javax.swing.JFrame {

    /**
     * Creates new form StokEkle
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public StokEkle() {
        initComponents();
           setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("PayposTableEkle32.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_barkod = new javax.swing.JTextField();
        txt_miktar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_kaydet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paypos Stok Ekle");
        setBounds(new java.awt.Rectangle(620, 330, 0, 0));
        setResizable(false);

        txt_barkod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_barkodFocusLost(evt);
            }
        });

        txt_miktar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_miktarFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Stok Ekle");

        btn_kaydet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paypostabloekle.png"))); // NOI18N
        btn_kaydet.setText("Stok Ekle");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Barkod");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Adet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_barkod, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_kaydet)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_barkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_miktar)))
                .addGap(18, 18, 18)
                .addComponent(btn_kaydet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_barkodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_barkodFocusLost
        // TODO add your handling code here:
        if(txt_barkod.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this,"Bos bırakamazsınız");
            txt_barkod.requestFocus();
        }
    }//GEN-LAST:event_txt_barkodFocusLost

    private void txt_miktarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_miktarFocusLost
        // TODO add your handling code here:
        if(txt_miktar.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(this,"Bos bırakamazsınız");
            txt_miktar.requestFocus();
        }
    }//GEN-LAST:event_txt_miktarFocusLost

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed
        // TODO add your handling code here:
        if (txt_barkod.getText().length()==0&&txt_miktar.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Stok kaydı başarısız..Barkod ve Adet  Alanları Doldurunuz");
        }
        else  if (txt_barkod.getText().length()!=0&&txt_miktar.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Ürün kaydı başarısız..Adet Alanını Doldurunuz");
        }
        else  if (txt_barkod.getText().length()==0&&txt_miktar.getText().length()!=0)
        {
            JOptionPane.showMessageDialog(null,"Ürün kaydı başarısız..Barkod  Alanını Doldurunuz");
        }
        else if (txt_barkod.getText().length()!=0 &&txt_miktar.getText().length()!=0)
        {
            int adetgelen=Integer.parseInt(txt_miktar.getText());
            int tablogelen;
            int a;
            String b = null;
            conn=db.db_java();
            String sql1="Select * From Stoklar Where Barkod=?";
            try 
            {
                  pst=conn.prepareStatement(sql1);
                  pst.setString(1,txt_barkod.getText());
                  rs=pst.executeQuery();
                  while (rs.next())
                  {                    
                    tablogelen=rs.getInt("Adet");
                    a=adetgelen+tablogelen;
                    b=String.valueOf(a);
                  }
            }
            catch (Exception e) 
            {
                
            }
            finally
            {
                try {
                    conn.close();
                }
                catch (Exception e) {
                }
            }
            conn=db.db_java();
            String sorgu="Update Stoklar SET Adet=? Where Barkod=?";
            try
            {
                pst=conn.prepareStatement(sorgu);
                pst.setString(1,b);
                pst.setString(2,txt_barkod.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Stok başarı ile kaydedildi..");
                txt_barkod.setText("");
                txt_miktar.setText("");
             }
            catch(Exception ex)
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null,"Stok kaydı başarısız.");
            }
            finally
            {
                try
                {
                    conn.close();
                }
                catch (Exception e) {
                }

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Lütfen Boş Alan veya Alanları Doldurunuz..");
        }
    }//GEN-LAST:event_btn_kaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_barkod;
    private javax.swing.JTextField txt_miktar;
    // End of variables declaration//GEN-END:variables
}
