
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class VeresiyeSatıs extends javax.swing.JFrame {

    /**
     * Creates new form VeresiyeSatıs
     */
     Connection conn=null;
     PreparedStatement pst=null;
     ResultSet rs=null;
    public VeresiyeSatıs() {
        initComponents();
        HomePage.veresiye=0;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("PyposVeresiyeSatıs32.png")));
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ad = new javax.swing.JTextField();
        txt_telefonno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_tutar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_soyad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paypos  Veresiye Kayıt");
        setBounds(new java.awt.Rectangle(620, 330, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Ad           :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Telefon no :");

        txt_ad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_adFocusLost(evt);
            }
        });

        txt_telefonno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telefonnoFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Veresiye Kayıt ");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payposkaydet.png"))); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Tutar        :");

        txt_tutar.setEditable(false);
        txt_tutar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tutarFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Soyad    :");

        txt_soyad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_soyadFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txt_ad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telefonno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_telefonno)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (txt_ad.getText().length()==0&&txt_soyad.getText().length()==0&&txt_telefonno.getText().length()==0&&txt_tutar.getText().length()==0)
        {
              JOptionPane.showMessageDialog(null,"Veresiye kaydı başarısız..Boş Alanları Doldurunuz");
        }
       else  if (txt_ad.getText().length()!=0&&txt_soyad.getText().length()==0&&txt_telefonno.getText().length()==0&&txt_tutar.getText().length()==0)
        {
              JOptionPane.showMessageDialog(null,"Veresiye kaydı başarısız..Soyad Telefon ve Tutar Alanlarını Doldurunuz");
        }
      else  if (txt_ad.getText().length()!=0&&txt_soyad.getText().length()!=0&&txt_telefonno.getText().length()==0&&txt_tutar.getText().length()==0)
        {
              JOptionPane.showMessageDialog(null,"Veresiye kaydı başarısız.. Telefon ve Tutar Alanlarını Doldurunuz");
        }
      else  if (txt_ad.getText().length()!=0&&txt_soyad.getText().length()!=0&&txt_telefonno.getText().length()!=0&&txt_tutar.getText().length()==0)
        {
              JOptionPane.showMessageDialog(null,"Veresiye kaydı başarısız..Tutar Alanını Doldurunuz");
        }   
      else if (txt_ad.getText().length()!=0 && txt_soyad.getText().length()!=0 && txt_telefonno.getText().length()!=0 && txt_tutar.getText().length()!=0) 
         {
            conn=db.db_java();
            String sorgu="INSERT INTO Veresiye (Ad,Soyad,Telefon,Tutar) VALUES (?,?,?,?)";
            try
                 {
               pst=conn.prepareStatement(sorgu);
               pst.setString(1,txt_ad.getText());
               pst.setString(2,txt_soyad.getText());
               pst.setString(3,txt_telefonno.getText());
               pst.setString(4,txt_tutar.getText());
               pst.execute();
              JOptionPane.showMessageDialog(null,"Veresiye başarı ile kaydedildi..");
              txt_ad.setText("");
              txt_soyad.setText("");
              txt_telefonno.setText("");
              txt_tutar.setText("");
              this.setVisible(false);
        }
      catch(Exception ex)
      {
         ex.printStackTrace();
          JOptionPane.showMessageDialog(null,"Veresiye kaydı başarısız..");
      }
      finally
      {
          try 
          {
           conn.close();
          }
          catch (Exception e) {
          }
   
      }
     }
      else
      {
          JOptionPane.showMessageDialog(null,"Lütfen Boş Alan veya Alanları Doldurunuz..");
      }
               
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_adFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_adFocusLost
        // TODO add your handling code here:
       if(txt_ad.getText().length() == 0) 
        {
            JOptionPane.showMessageDialog(this,"Bos bırakamazsınız");
            txt_ad.requestFocus();
        }
  
        
    }//GEN-LAST:event_txt_adFocusLost

    private void txt_soyadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_soyadFocusLost
        // TODO add your handling code here:
           if(txt_soyad.getText().length() == 0) 
           {
            JOptionPane.showMessageDialog(this,"Bos bırakamazsınız");
            txt_soyad.requestFocus();
           }
    }//GEN-LAST:event_txt_soyadFocusLost

    private void txt_telefonnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telefonnoFocusLost
        // TODO add your handling code here:
        if(txt_telefonno.getText().length() == 0) 
           {
            JOptionPane.showMessageDialog(this,"Bos bırakamazsınız");
            txt_telefonno.requestFocus();
           }
    }//GEN-LAST:event_txt_telefonnoFocusLost

    private void txt_tutarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tutarFocusLost
        // TODO add your handling code here:
        if(txt_tutar.getText().length() == 0) 
           {
            JOptionPane.showMessageDialog(this,"Bos bırakamazsınız");
            txt_tutar.requestFocus();
           }
    }//GEN-LAST:event_txt_tutarFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         txt_tutar.setText(HomePage.getToplam());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeresiyeSatıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeresiyeSatıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeresiyeSatıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeresiyeSatıs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeresiyeSatıs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_soyad;
    private javax.swing.JTextField txt_telefonno;
    private javax.swing.JTextField txt_tutar;
    // End of variables declaration//GEN-END:variables
}
