
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class ÖdemeYap extends javax.swing.JFrame {

    /**
     * Creates new form ÖdemeYap
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public ÖdemeYap() {
        initComponents();
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("PyposVeresiyeSatıs32.png")));
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ara = new javax.swing.JButton();
        btn_tumurunler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_urunler = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_ıd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_ad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_soyad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_telefon = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_tutar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paypos Ödeme Yap");
        setBounds(new java.awt.Rectangle(550, 230, 0, 0));
        setResizable(false);

        btn_ara.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PayposGoster.png"))); // NOI18N
        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        btn_tumurunler.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_tumurunler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PayposGoster.png"))); // NOI18N
        btn_tumurunler.setText("Tümünü Göster");
        btn_tumurunler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tumurunlerActionPerformed(evt);
            }
        });

        table_urunler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_urunler.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        table_urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ad", "Soyad", "Telefon", "Tutar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_urunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_urunlerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_urunlerMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_urunler);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("                        Veresiye Tablosu");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Müşteri Adını Giriniz:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Id:");

        lbl_ıd.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ad:");

        lbl_ad.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Soyad:");

        lbl_soyad.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Telefon:");

        lbl_telefon.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Tutar:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Belgeler\\New Folder\\PayPos\\src\\payposveresiyesatıs.png")); // NOI18N
        jButton1.setText("Kısmi Ödeme");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payposhesapkapat.png"))); // NOI18N
        jButton2.setText("Hesabı Kapat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tumurunler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_ıd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(btn_tumurunler))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_ıd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_ad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_tutar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_telefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)table_urunler.getModel();
        int row=model.getRowCount();
        for (int i =row-1; i >=0; i--)
        {
            model.removeRow(i);
        }
        try
        {
            conn=db.db_java();
            String sorgu="Select * From Veresiye WHERE Ad=?";
            pst=conn.prepareStatement(sorgu);
            pst.setString(1,txt_ad.getText());
            rs=pst.executeQuery();
            while (rs.next())
            {
                String ıdal=rs.getString("Id");
                String adal=rs.getString("Ad");
                String soyadal=rs.getString("Soyad");
                String telal=rs.getString("Telefon");
                String tutaral=rs.getString("Tutar");
                model.addRow(new Object[] {ıdal,adal,soyadal,telal,tutaral});
                txt_ad.setText("");

            }
        }
        catch (Exception e)
        {
            // JOptionPane.showMessageDialog(null,"Böyle bir ürün yok.");
        }
        finally
        {
            try
            {
                conn.close();
            }
            catch (Exception e)
            {

            }
        }
    }//GEN-LAST:event_btn_araActionPerformed

    private void btn_tumurunlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tumurunlerActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)table_urunler.getModel();
        txt_ad.setText("");
        int row=model.getRowCount();
        for (int i =row-1; i >=0; i--)
        {
            model.removeRow(i);
        }
        try
        {
            conn=db.db_java();
            String sorgu="Select * From Veresiye";
            pst=conn.prepareStatement(sorgu);
            rs=pst.executeQuery();
            while (rs.next())
            {
                String ıdal=rs.getString("Id");
                String adal=rs.getString("Ad");
                String soyadal=rs.getString("Soyad");
                String telal=rs.getString("Telefon");
                String tutaral=rs.getString("Tutar");
                model.addRow(new Object[] {ıdal,adal,soyadal,telal,tutaral});
            }
        }
        catch (Exception e)
        {
            // JOptionPane.showMessageDialog(null,"Böyle bir ürün yok.");
        }
        finally
        {
            try
            {
                conn.close();
            }
            catch (Exception e)
            {

            }
        }
    }//GEN-LAST:event_btn_tumurunlerActionPerformed

    private void table_urunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_urunlerMouseClicked
        // TODO add your handling code here:
        lbl_ıd.setText(table_urunler.getValueAt(table_urunler.getSelectedRow(),0).toString());
        lbl_ad.setText(table_urunler.getValueAt(table_urunler.getSelectedRow(),1).toString());
        lbl_soyad.setText(table_urunler.getValueAt(table_urunler.getSelectedRow(),2).toString());
        lbl_telefon.setText(table_urunler.getValueAt(table_urunler.getSelectedRow(),3).toString());
     
    }//GEN-LAST:event_table_urunlerMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) table_urunler.getModel();
        int secilen=table_urunler.getSelectedRow();
        int gelentutar=Integer.parseInt(table_urunler.getValueAt(table_urunler.getSelectedRow(),4).toString());
        int tutar=Integer.parseInt(txt_tutar.getText());
         conn=db.db_java();
        if(table_urunler.getSelectedRow()>=0&&tutar!=0)
       {
         gelentutar-=tutar;
         jLabel4.setText(String.valueOf(gelentutar));
           if (gelentutar<=0)
           {
             String sorgu="Delete From Veresiye Where Id=?;";
            try 
                 {
              
                     pst=conn.prepareStatement(sorgu);
                     pst.setString(1,lbl_ıd.getText());
                     pst.execute();
                     JOptionPane.showMessageDialog(null,"Veresiye Silinmiştir.!");
                     model.removeRow(secilen);
                     lbl_ad.setText("");
                     lbl_soyad.setText("");
                     lbl_telefon.setText("");
                     lbl_ıd.setText("");
                     txt_tutar.setText("");                     
                  }
         catch (Exception e) 
           {
               JOptionPane.showMessageDialog(null,"Veresiye Silinemedi.!");
           }
          finally
               {
                     try 
                         {
                          conn.close();
                         }
                    catch (Exception e) 
                         {
                
                          } 
              }
           }
       else
       {  
        
         String sql="Update Veresiye SET tutar=? Where Id=?";
        try 
        {
             pst=conn.prepareStatement(sql);
             pst.setString(1,jLabel4.getText());
             pst.setString(2,lbl_ıd.getText());
             pst.executeUpdate();        
             JOptionPane.showMessageDialog(null,"Kısmi Ödeme Yapıldı.");
             lbl_ad.setText("");
             lbl_soyad.setText("");
             lbl_telefon.setText("");
             lbl_ıd.setText("");
             txt_tutar.setText("");
             int row=model.getRowCount();
              for (int i =row-1; i >=0; i--)  
              {                         
                  model.removeRow(i);
              }     
         }
        catch (Exception e) 
                 {
                     JOptionPane.showMessageDialog(null,"Lütfen Ödeme Yapacağınız Kayıtı Seçiniz.Veya Kısmı Ödeme Tutarınız Giriniz.");
                 }
        finally
               {
                 try 
                    {
                      conn.close();
                      }
                 catch (Exception e)
                     {
                
                    }
               }
          }
       }
       
                  
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txt_tutar.setText(table_urunler.getValueAt(table_urunler.getSelectedRow(),4).toString());
        txt_tutar.isEditable();
        DefaultTableModel model=(DefaultTableModel) table_urunler.getModel();
        int secilen=table_urunler.getSelectedRow();
        conn=db.db_java();
       // String sql="Delete Veresiye SET tutar=? Where Id=?";
       String sorgu="Delete From Veresiye Where Id=?;";
         try 
          {
              
                     pst=conn.prepareStatement(sorgu);
                     pst.setString(1,lbl_ıd.getText());
                     pst.execute();
                     JOptionPane.showMessageDialog(null,"Hesap Kapatıldı.Veresiye Silinmiştir.!");
                     model.removeRow(secilen);
                     lbl_ad.setText("");
                     lbl_soyad.setText("");
                     lbl_telefon.setText("");
                     lbl_ıd.setText("");
                     txt_tutar.setText("");                     
           }
         catch (Exception e) 
           {
                       e.printStackTrace();
                       JOptionPane.showMessageDialog(null,"Veresiye Silinemedi.!");
           }
          finally
               {
                     try 
                         {
                          conn.close();
                         }
                    catch (Exception e) 
                         {
                
                          } 
              }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_urunlerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_urunlerMousePressed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_table_urunlerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÖdemeYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÖdemeYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÖdemeYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÖdemeYap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÖdemeYap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_tumurunler;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ad;
    private javax.swing.JLabel lbl_soyad;
    private javax.swing.JLabel lbl_telefon;
    private javax.swing.JLabel lbl_ıd;
    private javax.swing.JTable table_urunler;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_tutar;
    // End of variables declaration//GEN-END:variables
}
